/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.validation;

import org.xtext.example.validation.AbstractDirFileValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DirFileValidator extends AbstractDirFileValidator {
}
