/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDirFileScopeProvider extends DelegatingScopeProvider {
}
