/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example;

import org.xtext.example.AbstractDirFileRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DirFileRuntimeModule extends AbstractDirFileRuntimeModule {
}
