/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example;

import org.xtext.example.DirFileStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DirFileStandaloneSetup extends DirFileStandaloneSetupGenerated {
  public static void doSetup() {
    new DirFileStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
