/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DirFileStandaloneSetup extends DirFileStandaloneSetupGenerated {

	def static void doSetup() {
		new DirFileStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
