/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.dirfile.ui.internal.DirfileActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DirFileExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DirfileActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DirfileActivator activator = DirfileActivator.getInstance();
		return activator != null ? activator.getInjector(DirfileActivator.ORG_XTEXT_EXAMPLE_DIRFILE) : null;
	}

}
