/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.ide;

import org.xtext.example.ide.AbstractDirFileIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DirFileIdeModule extends AbstractDirFileIdeModule {
}
