/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.DirFileRuntimeModule;
import org.xtext.example.DirFileStandaloneSetup;
import org.xtext.example.ide.DirFileIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DirFileIdeSetup extends DirFileStandaloneSetup {
  @Override
  public Injector createInjector() {
    DirFileRuntimeModule _dirFileRuntimeModule = new DirFileRuntimeModule();
    DirFileIdeModule _dirFileIdeModule = new DirFileIdeModule();
    return Guice.createInjector(Modules2.mixin(_dirFileRuntimeModule, _dirFileIdeModule));
  }
}
