/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.ui.AbstractDirFileUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DirFileUiModule extends AbstractDirFileUiModule {
  public DirFileUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
