/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalDirFileParser;
import org.xtext.example.services.DirFileGrammarAccess;

public class DirFileParser extends AbstractAntlrParser {

	@Inject
	private DirFileGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDirFileParser createParser(XtextTokenStream stream) {
		return new InternalDirFileParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Directory";
	}

	public DirFileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DirFileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
