/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.dirFile.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.dirFile.DirFilePackage;
import org.xtext.example.dirFile.File;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FileImpl extends TYPE_DIR_FILEImpl implements File
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DirFilePackage.Literals.FILE;
  }

} //FileImpl
