/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.dirFile;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directory</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dirFile.Directory#getTree <em>Tree</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dirFile.DirFilePackage#getDirectory()
 * @model
 * @generated
 */
public interface Directory extends TYPE_DIR_FILE
{
  /**
   * Returns the value of the '<em><b>Tree</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.dirFile.TYPE_DIR_FILE}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tree</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tree</em>' containment reference list.
   * @see org.xtext.example.dirFile.DirFilePackage#getDirectory_Tree()
   * @model containment="true"
   * @generated
   */
  EList<TYPE_DIR_FILE> getTree();

} // Directory
