/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.dirFile;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.dirFile.DirFilePackage#getFile()
 * @model
 * @generated
 */
public interface File extends TYPE_DIR_FILE
{
} // File
