/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.dirFile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>First Directory</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dirFile.FirstDirectory#getFirstDirectory <em>First Directory</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dirFile.DirFilePackage#getFirstDirectory()
 * @model
 * @generated
 */
public interface FirstDirectory extends EObject
{
  /**
   * Returns the value of the '<em><b>First Directory</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>First Directory</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Directory</em>' containment reference.
   * @see #setFirstDirectory(Directory)
   * @see org.xtext.example.dirFile.DirFilePackage#getFirstDirectory_FirstDirectory()
   * @model containment="true"
   * @generated
   */
  Directory getFirstDirectory();

  /**
   * Sets the value of the '{@link org.xtext.example.dirFile.FirstDirectory#getFirstDirectory <em>First Directory</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Directory</em>' containment reference.
   * @see #getFirstDirectory()
   * @generated
   */
  void setFirstDirectory(Directory value);

} // FirstDirectory
